echo ""
echo ""
echo ""
echo "When prepping a Pull Request, make sure you do the following:"
echo ""
echo ""
echo "Test"
echo "1. Run 'yarn build' to ensure tests pass and the app builds successfully."
echo ""
echo ""
echo "Review Commit"
echo "0. Unit tests written."
echo "1. Ensure commit does one thing and one thing only."
echo "2. Ensure commit title is descriptive/concise"
echo "3. Ensure commit message is descriptive/concise"
echo ""
echo ""
echo ""